docs(README): fix typos
KevinEdry/nestjs-trpc pull request #10
Opened 2024-09-28 17:42 UTC by Mnigos

Fixing simple typos inside `README.md`

Also I'm suggesting to embed a gif that really uses `nestjs-trpc` and not vanilla trpc server.

2024-09-28 18:08 UTC, KevinEdry commented
I am painfully aware that this readme isn't in the best shape 😅, I've mentioned it in the original trpc issue. Would you mind adding the gif to this PR?

2024-09-28 19:13 UTC, Mnigos commented
> I am painfully aware that this readme isn't in the best shape 😅, I have spent too much time on the docs and neglected this readme, I think I also mentioned it in the original trpc issue. Would you mind adding the gif to this PR?

Sure!

2024-09-29 16:03 UTC, Mnigos commented
@KevinEdry I Edited code formatting a little bit let me know what you are thinking, but I'm not sure what `@Procedure` decorator and `ProtectedProcedure` are doing. Is it like a guard for tRPC? I don't see it covered anywhere in documentation.

2024-09-30 04:17 UTC, KevinEdry requested changes
> @KevinEdry I Edited code formatting a little bit let me know what are you thinking, but I'm not sure what `@Procedure` decorator and `ProtectedProcedure` are doing. Is it like a guard for tRPC? I don't see it covered anywhere in documentation.

The `@Procedure` is the previous implementation of [Middlewares](https://www.nestjs-trpc.io/docs/middlewares). The docs are updated with the correct examples.

Looks good overall, there are still a couple of things that needs to be corrected.
Thanks for taking the time to do this!

2024-09-30 04:17 UTC, KevinEdry commented on README.md
> +npm install trpc-nestjs zod
We should also add the `@trpc/server` here since both `zod` and `@trpc/server` are peer dependencies.

2024-09-30 04:17 UTC, KevinEdry commented on README.md
> -    @Inject(UserService) private readonly userService: UserService
I'd rather move this to the top and keep the Idiomatic way of the `@Inject()` decorator to emphasis that DI works seamlessly with this library.

2024-09-30 04:17 UTC, KevinEdry commented on README.md
> +      throw new TRPCError("An error has occured when trying to get users.", "INTERNAL_SERVER_ERROR", error)
In general, the way I handle errors here isn't correct, see https://trpc.io/docs/v10/server/error-handling
I need to pass an object rather then single parameters here.

2024-09-30 06:57 UTC, Mnigos commented
@KevinEdry I've applied your requested changes and removed some deprecated code from husky hook.

2024-10-01 00:34 UTC, merged

2024-10-01 10:23 UTC, Mnigos commented
> Looks awesome, thanks for helping with the README file! I wish there was also a gif using the library, but it's not a must-have.

I will try to dedicate some of my time to create this gif